<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE SERVICE_MAPPINGS [
	<!ELEMENT SERVICE_MAPPINGS (SERVICE*)>
	<!ELEMENT SERVICE (NAME,BEAN_HOME_INTF)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT BEAN_HOME_INTF (#PCDATA)>
]>

<SERVICE_MAPPINGS>
	<SERVICE>
		<NAME>sCreate_myclassreveng_74764e10dc25a106_7856b454e0583d3c(LCompTest.myclassreveng)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>sModify_myclassreveng_55b5d1f221d5504c_352e7dcbb09d1a2b(LCompTest.myclassreveng)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>sDelete_myclassreveng_f54ecd33d0e43262_6805f84f597b57b6(LCompTest.myclassreveng)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>sGet_myclassreveng_43e93aeb109fe734_a064536d020eb7c7(LCompTest.myclassreveng)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>sGetAll_myclassreveng_b7dced52ea3d7d06_b6e3be734121812d(LCompTest.myclassreveng)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>sSubmitGrid_myclassreveng_bc92e9ecdd977cd9_31d639ae8c4e72ee(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>sDeleteRows_myclassreveng_88ba6bd1653dc30e_195733da81ecbe2d(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>CompTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
</SERVICE_MAPPINGS>
