<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE SERVICE_MAPPINGS [
	<!ELEMENT SERVICE_MAPPINGS (SERVICE*)>
	<!ELEMENT SERVICE (NAME,BEAN_HOME_INTF)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT BEAN_HOME_INTF (#PCDATA)>
]>

<SERVICE_MAPPINGS>
	<SERVICE>
		<NAME>serv_create_9451186e5c8c8bd7_89d773b1890c914f(LCaseStudyTest.CustDetails)</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_search_ecc2ec0ab12fdffb_c931984ac806c948(LCaseStudyTest.CustDetails)</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_update_32d46ef3c74d53fb_20d3275528d39e0c(LCaseStudyTest.CustDetails)</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_delete_f03b66342649eb25_d15a15da92e1e48e(LCaseStudyTest.CustDetails)</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_test_c513fd4c205e9c27_a4aa53c1a3b5b847(LCaseStudyTest.CustDetails)</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_test1_45cf637942390db1_3b530948aed285f9(LCaseStudyTest.CustDetails)</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>vbn_d2ae5f46b2a09685_337d81e32df99c40()</NAME>
		<BEAN_HOME_INTF>CaseStudyTestBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
</SERVICE_MAPPINGS>
